import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import Lenis from "lenis";
import { motion, useInView, useMotionValue, useScroll, useSpring } from "motion/react";
import { ArrowDown, ArrowRight, ArrowUpRight, Building2, CheckCircle2, Compass, Hammer, Mail, MapPin, Menu, Phone, Store, X } from "lucide-react";
import "./styles.css";

const services=[
{icon:Compass,title:"Diseño y arquitectura",text:"Espacios pensados para unir estética, funcionalidad y una visión duradera."},
{icon:Building2,title:"Construcción",text:"Ejecución técnica con planificación precisa y control de calidad en cada etapa."},
{icon:Store,title:"Comercial e industrial",text:"Soluciones eficientes para negocios, desarrollos y espacios de alto rendimiento."},
{icon:Hammer,title:"Gestión de proyectos",text:"Coordinamos personas, recursos y tiempos para convertir ideas en resultados."}
];
const projects=[
["01","Residencial Aurora","Desarrollo residencial multifamiliar","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=90"],
["02","Plaza Central","Centro comercial contemporáneo","https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=90"],
["03","Villa Horizonte","Remodelación integral de vivienda","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=90"]
];
const steps=[["01","Escuchamos","Entendemos tus necesidades, objetivos y la personalidad de tu proyecto."],["02","Diseñamos","Creamos una solución estratégica que equilibra forma, función y presupuesto."],["03","Construimos","Ejecutamos con control, coordinación y atención permanente a los detalles."],["04","Entregamos","Cerramos cada proyecto con calidad y la seguridad de un trabajo bien hecho."]];

function Reveal({children,delay=0,y=30,className=""}){const r=useRef(null),v=useInView(r,{once:true,margin:"-10% 0px"});return <motion.div ref={r} className={className} initial={{opacity:0,y,filter:"blur(9px)"}} animate={v?{opacity:1,y:0,filter:"blur(0px)"}:{}} transition={{duration:.75,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function SplitText({children,delay=0}){const r=useRef(null),v=useInView(r,{once:true});return <span ref={r} className="split">{String(children).split(" ").map((w,i)=><span className="word-wrap" key={i}><motion.span className="word" initial={{y:"120%",opacity:0,filter:"blur(10px)"}} animate={v?{y:0,opacity:1,filter:"blur(0px)"}:{}} transition={{duration:.8,delay:delay+i*.075,ease:[.22,1,.36,1]}}>{w}{i<String(children).split(" ").length-1?"\u00a0":""}</motion.span></span>)}</span>}
function Count({end,suffix=""}){const r=useRef(null),v=useInView(r,{once:true}),mv=useMotionValue(0),s=useSpring(mv,{stiffness:60,damping:18}),[n,setN]=useState(0);useEffect(()=>{if(v)mv.set(end)},[v,end,mv]);useEffect(()=>s.on("change",x=>setN(Math.round(x))),[s]);return <strong ref={r}>{n}{suffix}</strong>}
function Magnetic({children,className,onClick,type="button"}){const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:180,damping:14}),sy=useSpring(y,{stiffness:180,damping:14});return <motion.button type={type} className={className} style={{x:sx,y:sy}} onMouseMove={e=>{const b=e.currentTarget.getBoundingClientRect();x.set((e.clientX-b.left-b.width/2)*.12);y.set((e.clientY-b.top-b.height/2)*.12)}} onMouseLeave={()=>{x.set(0);y.set(0)}} onClick={onClick}>{children}</motion.button>}
function App(){const [menu,setMenu]=useState(false),[active,setActive]=useState("inicio"),[loginOpen,setLoginOpen]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[user,setUser]=useState(()=>JSON.parse(localStorage.getItem("aurea_user")||"null")),[error,setError]=useState("");const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:120,damping:30});
const login=e=>{e.preventDefault();const users={"admin@aurea.cr":{password:"admin123",name:"Administrador ÁUREA",role:"admin"},"persona@aurea.cr":{password:"persona123",name:"Usuario ÁUREA",role:"persona"}};const found=users[email.trim().toLowerCase()];if(!found||found.password!==password){setError("Correo o contraseña incorrectos");return;}const next={name:found.name,role:found.role,email:email.trim().toLowerCase()};localStorage.setItem("aurea_user",JSON.stringify(next));setUser(next);setLoginOpen(false);setError("");setPassword("");};
const logout=()=>{localStorage.removeItem("aurea_user");setUser(null);};
const openAdmin=()=>{if(user?.role==="admin")window.location.href="http://localhost:9173/production/index.html?auth=aurea-admin";};
useEffect(()=>{const lenis=new Lenis({duration:1.1,smoothWheel:true});let id;const raf=t=>{lenis.raf(t);id=requestAnimationFrame(raf)};id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy()}},[]);
const go=id=>{setMenu(false);setActive(id);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
return <><motion.div className="progress" style={{scaleX:progress}}/><header className="nav"><button className="brand" onClick={()=>go("inicio")}><span className="brand-mark">A</span><span>ÁUREA</span></button><nav className={menu?"links open":"links"}>{[["inicio","Inicio"],["servicios","Servicios"],["proyectos","Proyectos"],["nosotros","Nosotros"]].map(([id,n])=><button key={id} className={active===id?"active":""} onClick={()=>go(id)}>{n}</button>)}<button className="mobile-cta" onClick={()=>go("contacto")}>Solicitar cotización</button></nav><Magnetic className="cta" onClick={()=>go("contacto")}>Solicitar cotización <ArrowRight size={17}/></Magnetic><div className="auth-actions">{user?.role==="admin"&&<button className="admin-access" onClick={openAdmin}>Panel Admin</button>}{user?<button className="account-btn" onClick={logout}>Salir · {user.role==="admin"?"Admin":"Persona"}</button>:<button className="account-btn" onClick={()=>setLoginOpen(true)}>Iniciar sesión</button>}</div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section id="inicio" className="hero"><motion.div className="hero-bg" initial={{scale:1.12}} animate={{scale:1}} transition={{duration:2.2,ease:[.22,1,.36,1]}}/><div className="noise"/><div className="shade"/><div className="hero-copy"><motion.div className="eyebrow light" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.2}}><span/>ARQUITECTURA · CONSTRUCCIÓN · INNOVACIÓN</motion.div><h1><SplitText delay={.35}>Construimos</SplitText><em><SplitText delay={.55}>espacios</SplitText></em><SplitText delay={.75}>que trascienden.</SplitText></h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:1.05}}>Transformamos ideas en proyectos excepcionales con diseño inteligente, ejecución precisa y una atención cercana.</motion.p><motion.div className="hero-actions" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:1.2}}><Magnetic className="primary" onClick={()=>go("contacto")}>Hablemos de tu proyecto <ArrowUpRight size={18}/></Magnetic><button className="text-btn" onClick={()=>go("proyectos")}>Ver proyectos <ArrowRight size={18}/></button></motion.div></div><div className="stats"><div><Count end={12} suffix="+"/><span>Años creando</span></div><div><Count end={80} suffix="+"/><span>Proyectos realizados</span></div><div><Count end={100} suffix="%"/><span>Compromiso</span></div></div><button className="discover" onClick={()=>go("servicios")}><span>DESCUBRE</span><ArrowDown size={16}/></button></section>
<section id="servicios" className="section"><div className="head"><Reveal><div className="eyebrow">NUESTROS SERVICIOS</div><h2>Soluciones integrales<br/>para tu proyecto.</h2></Reveal><Reveal delay={.15}><p>Desde la primera idea hasta la entrega final, acompañamos cada decisión con experiencia, claridad y excelencia.</p></Reveal></div><div className="services">{services.map((s,i)=>{const I=s.icon;return <Reveal key={s.title} delay={i*.1} y={45}><motion.article className="service" whileHover={{y:-8}} transition={{type:"spring",stiffness:260,damping:20}}><span className="num">0{i+1}</span><motion.div className="icon" whileHover={{rotate:-7,scale:1.08}}><I/></motion.div><h3>{s.title}</h3><p>{s.text}</p><button data-cursor="VER" onClick={()=>go("contacto")}><ArrowUpRight size={21}/></button></motion.article></Reveal>})}</div></section>
<section id="nosotros" className="vision"><Reveal className="vision-img-wrap" y={0}><motion.div className="vision-img" initial={{clipPath:"inset(0 100% 0 0)"}} whileInView={{clipPath:"inset(0 0 0 0)"}} viewport={{once:true}} transition={{duration:1.2,ease:[.22,1,.36,1]}}/></Reveal><div className="vision-copy"><Reveal><div className="eyebrow light">NUESTRA VISIÓN</div></Reveal><Reveal delay={.08}><h2>No solo construimos edificios.<br/><em>Construimos confianza.</em></h2></Reveal><Reveal delay={.16}><p>Creemos que los mejores proyectos nacen de una conversación honesta. Por eso combinamos creatividad, técnica y una forma de trabajar transparente.</p></Reveal><div className="checks">{["Comunicación clara","Calidad en cada detalle","Entregas responsables"].map((t,i)=><Reveal key={t} delay={.2+i*.1}><div><CheckCircle2 size={20}/>{t}</div></Reveal>)}</div></div></section>
<section id="proyectos" className="section projects"><div className="head"><Reveal><div className="eyebrow">PROYECTOS DESTACADOS</div><h2>Espacios con identidad.</h2></Reveal><Reveal delay={.15}><Magnetic className="outline" onClick={()=>go("contacto")}>Explorar más proyectos <ArrowRight size={18}/></Magnetic></Reveal></div><div className="project-grid">{projects.map((p,i)=><Project key={p[0]} p={p} i={i}/>)}</div></section>
<section className="process"><Reveal><div className="process-title"><div className="eyebrow">NUESTRO PROCESO</div><h2>De la visión<br/>a la realidad.</h2></div></Reveal><div className="step-list">{steps.map((s,i)=><Step key={s[0]} s={s} d={i*.08}/>)}</div></section>
<section id="contacto" className="contact"><div><Reveal><div className="eyebrow light">EMPECEMOS</div></Reveal><Reveal delay={.08}><h2>Tu próximo proyecto<br/><em>comienza aquí.</em></h2></Reveal><Reveal delay={.16}><p>Cuéntanos qué tienes en mente. Nuestro equipo estará encantado de ayudarte a darle forma.</p></Reveal><div className="contact-info">{[[Phone,"+506 2222 0000"],[Mail,"hola@aurea.cr"],[MapPin,"San José, Costa Rica"]].map(([I,t],i)=><Reveal key={t} delay={.2+i*.08}><span><I size={18}/>{t}</span></Reveal>)}</div></div><Reveal delay={.15}><motion.form className="form" onSubmit={e=>{e.preventDefault();alert("¡Gracias! Hemos recibido tu solicitud.")}} initial={{opacity:0,y:35,scale:.98}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true}} transition={{duration:.8}}><label>Nombre<input required placeholder="Tu nombre"/></label><label>Correo electrónico<input required type="email" placeholder="tu@correo.com"/></label><label>Tipo de proyecto<select defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Residencial</option><option>Comercial</option><option>Remodelación</option><option>Otro</option></select></label><label>Cuéntanos un poco<textarea required rows="4" placeholder="Describe tu idea..."/></label><Magnetic type="submit" className="primary submit">Enviar solicitud <ArrowRight size={18}/></Magnetic></motion.form></Reveal></section></main>
<footer><div className="footer-top"><div><div className="footer-brand"><span className="brand-mark">A</span> ÁUREA</div><p>Arquitectura y construcción con una mirada contemporánea y humana.</p></div><div className="footer-links"><div><strong>Empresa</strong><button onClick={()=>go("inicio")}>Inicio</button><button onClick={()=>go("nosotros")}>Nosotros</button><button onClick={()=>go("proyectos")}>Proyectos</button></div><div><strong>Servicios</strong><button onClick={()=>go("servicios")}>Arquitectura</button><button onClick={()=>go("servicios")}>Construcción</button><button onClick={()=>go("servicios")}>Gestión</button></div></div></div><div className="footer-bottom"><span>© 2026 Áurea Construcción. Todos los derechos reservados.</span><span>Privacidad · Términos</span></div></footer>{loginOpen&&<div className="login-overlay" role="dialog" aria-modal="true"><div className="login-card"><button className="login-close" onClick={()=>setLoginOpen(false)}><X size={20}/></button><span className="login-kicker">ÁUREA · ACCESO</span><h2>Bienvenido</h2><p>Ingresa con tu cuenta para acceder a tu experiencia.</p><form onSubmit={login}><label>Correo<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="admin@aurea.cr" required/></label><label>Contraseña<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="••••••••" required/></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" type="submit">Entrar <ArrowRight size={17}/></button></form><div className="demo-users"><strong>Cuentas de prueba</strong><span>Admin: admin@aurea.cr / admin123</span><span>Persona: persona@aurea.cr / persona123</span></div></div></div>}</>}
function Project({p,i}){const r=useRef(null),v=useInView(r,{once:true,margin:"-12% 0px"});return <motion.article ref={r} className={`project p${i}`} initial={{opacity:0,y:45}} animate={v?{opacity:1,y:0}:{}} transition={{duration:.8,delay:i*.1}}><motion.div className="project-img" data-cursor="VER" style={{backgroundImage:`url(${p[3]})`}} initial={{scale:1.12,filter:"blur(8px)"}} animate={v?{scale:1,filter:"blur(0px)"}:{}} transition={{duration:1.15,ease:[.22,1,.36,1]}}><span className="project-num">{p[0]}</span><span className="project-action">Ver proyecto <ArrowUpRight size={17}/></span></motion.div><div className="project-info"><h3>{p[1]}</h3><p>{p[2]}</p></div></motion.article>}
function Step({s,d}){const r=useRef(null),v=useInView(r,{once:true,margin:"-20% 0px"});return <motion.div ref={r} className="step" initial={{opacity:.35,x:16}} animate={v?{opacity:1,x:0}:{}} transition={{duration:.65,delay:d}}><span className={v?"active-step":""}>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></motion.div>}
createRoot(document.getElementById("root")).render(<App/>);
